steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_BASE=${_API_BASE}
      - -t
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args: [push, "${_IMAGE}"]

substitutions:
  _API_BASE: ""
  _IMAGE: ""

images:
  - ${_IMAGE}

options:
  logging: CLOUD_LOGGING_ONLY
